### ISSUE TITLE
Clan API: Wrong player tag

### ISSUE THREAD

**Issue by RafAtreides** [cr-api/cr-api#58] opened 2017-10-18 19:30 UTC
http://api.cr-api.com/clan/20QJRQ00
members section

name: "малик_регион123"
tag: 9PCV9R8V

this tag is wrong, http://api.cr-api.com/profile/9PCV9R8V in not exist
right tag is 9829JJVR9 (http://statsroyale.com/profile/9829JJVR9)

it's a bug?

**Comment by selfish** [comment] 2017-10-18 20:28
The root of the problem is the same as #10.
Will be fixed soon. 
Thanks for reporting!

**Comment by selfish** [comment] 2017-10-31 17:40
Fixed in v6.0.0

**Closed by selfish** 2017-10-31 17:40 UTC
Labels: bug, important
