### ISSUE TITLE
not returned arenaID

### ISSUE THREAD

**Issue by anksite** [cr-api/cr-api#248] opened 2018-02-18 03:09 UTC
When  I request player data, some time the arenaID not returned by the server

```
"tag": "29982Q0P",
  "name": "ADNAN",
  "trophies": 3426,
  "rank": null,
  "arena": {
    "name": "Arena 11"
  },

```

**Comment by fourjr** [comment] 2018-02-18 07:40
Dupe of #243

**Closed by fourjr** 2018-02-18 07:40 UTC
